### ISSUE TITLE
電力に余裕ができたらレーザータレットを配置したい

### ISSUE THREAD

**Issue by n-elra** [unity-game-dev-guild/factorio#4]

**Comment by n-elra** [comment]
ソーラーだけでは今後の需要を賄うのは厳しそうなので原発が必要かも

**Comment by naichilab** [comment]
原発めっちゃ大変そうですね、、、

**Comment by n-elra** [comment]
この調子でソーラー増やしていけば電力大丈夫かも

**Comment by n-elra** [comment]
レーザータレットは製作コストに対して性能微妙そうなので
建設ロボットで一括配置が楽にできるまでは保留

**Comment by n-elra** [comment]
太陽光発電で十分な電力を確保できてるので一部レーザータレットに置き換え済み
